<template>
  <div>
    <p class="text-md pb-12">‘Drones’. The word sends a shiver down the backs of many people, and rightly so. Drones have recently become notorious for their lethal activities in the Middle East, and people are afraid that they will be used at home. In the United States of America, citizens are becoming aware of the increasing use of ‘Unmanned Aerial Vehicles’ by law enforcements agencies. This is leading to a lot of propositions for new legislations, and while these may seem good at first, what does this really mean? These legislations would negatively affect the rising community of drone hobbyists, who use drones purely for their own entertainment or for filming purposes. These people would be stripped of their hobby, while doing nothing wrong. While these laws are just being lobbied for in the United States of America at the moment, they are raising awareness about drones in other countries, such as New Zealand. If America passes laws about drones, New Zealand will most likely follow. Is this really what we want?</p>
    <p class="text-md pb-12">There is also another group of people who use drones: the hobbyist community. These people build small drones purely for their own entertainment and would be stripped of their hobby by these legislations. These hobbyist drones can range from small remote control helicopters or planes with cameras attached to larger models with fully functioning waypoint and autopilot systems. While this may frighten some people at first, there is nothing inherently threatening about this. So far, the model community has been generally left to police themselves, with a few regulations to govern them. This has actually worked very well so far, with people using common sense and flying their models over large open spaces, and not doing low passes over their neighbourhood. Of course, there are always those few people who ignore caution and do dangerous things, and sadly these are the ones we hear about. However, this can apply to everything, as generally everyone drives carefully, but there are always those few people who ignore common sense and drive under the influence of alcohol, and this is the cause of a lot of the car crashes we hear about in the news. </p>
    <p class="text-md pb-12">Drones are feared around the world, and perhaps the have earned this fear through the United States Military. But drones are used for many peaceful and safe purposes around the world, where they abolish the need of putting someone’s life into risk. A lot of people do not seem to realise this, and just want drones to be banned. I believe this would be a bad thing, as it would severely cripple the industry and hobby of many. While laws and regulations do need to be revised to match the new technology available, this should be thought of carefully, with all sides of the debate taken into close account.</p>
  </div>
</template>



